{
    "name": "AlphaQueb · Portal de Control Administrativo",
    "summary": "Portal web externo (React) con usuarios propios para la coordinación administrativa y el control operativo de AlphaQueb",
    "version": "19.0.1.0.0",
    "category": "Services/Administration",
    "author": "Alphaqueb",
    "website": "https://alphaqueb.com",
    "license": "LGPL-3",
    "depends": ["base", "mail", "account"],
    "external_dependencies": {"python": ["passlib", "requests"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "data/procedure_steps.xml",
        "data/routines.xml",
        "data/onboarding_deliverables.xml",
        "data/initial_portfolio.xml",
        "data/mail_templates.xml",
        "data/ir_cron.xml",
        "data/ops_templates.xml",
        "data/ops_automations.xml",
        "data/ops_seed.xml",
        "data/google.xml",
        "views/portal_user_views.xml",
        "views/backend_views.xml",
        "views/menus.xml",
        "views/ops_menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
