# -*- coding: utf-8 -*-
"""Registro de recursos de Operaciones. Permisos por perfil (RBAC) + alcance por organización/proyecto (ABAC) + redacción de campos."""
from ..models.ops_security import FULL_ROLES, INTERNAL_ROLES, RESTRICTED_ROLES, CLIENT_ROLES

FULL = sorted(FULL_ROLES)
INTERNAL = sorted(FULL_ROLES | INTERNAL_ROLES)
TEAM = sorted(FULL_ROLES | INTERNAL_ROLES | RESTRICTED_ROLES)
CLIENT = sorted(CLIENT_ROLES)
EVERYONE = sorted(FULL_ROLES | INTERNAL_ROLES | RESTRICTED_ROLES | CLIENT_ROLES | {"observer"})
CLIENT_APPROVERS = ["client_sponsor", "client_po", "client_validator"]
LEADS = sorted(FULL_ROLES | {"pm", "functional_lead", "tech_lead"})
CLIENT_HIDDEN_COMMON = ["internal_notes", "escalation_path", "blocked_reason", "hours_estimated", "estimate_hours", "remaining_hours", "spent_hours", "transcript", "ai_summary",
                        "ai_proposals_json", "found_in", "is_rework", "unplanned", "reschedule_reason", "portal_create_user_id", "portal_write_user_id", "notes"]

OPS_SECTIONS = [
    {"key": "trabajo", "label": "Ejecución"}, {"key": "gobierno", "label": "Gobierno de entrega"}, {"key": "calidad", "label": "Calidad y liberaciones"},
    {"key": "tiempo", "label": "Tiempo y capacidad"}, {"key": "conocimiento", "label": "Conocimiento y comunicación"}, {"key": "config", "label": "Configuración"},
]

OPS_RESOURCES = {
    "projects": {
        "model": "aq.ops.project", "label": "Proyectos", "singular": "Proyecto", "section": "trabajo", "order": 10, "attachments": True, "chatter": True, "scope": "id",
        "list": ["name", "partner_id", "pm_id", "service_type", "stage", "health", "priority", "risk_level", "hours_pct", "next_milestone_id", "next_action_date", "client_dependent"],
        "filters": ["stage", "health", "service_type", "priority", "risk_level", "pm_id", "partner_id", "client_dependent", "has_next_action"],
        "groups": [
            {"title": "Identidad", "fields": ["name", "code", "partner_id", "service_type", "template_id", "methodology", "stage", "priority", "client_visible"]},
            {"title": "Sesiones y documentos", "fields": ["session_prefix", "session_seq", "session_po", "group_email", "session_count", "drive_folder_id", "drive_folder_url"]},
            {"title": "Objetivo y alcance vigente", "fields": ["objective", "scope_current", "scope_version", "admin_project_ref"]},
            {"title": "Equipo", "fields": ["pm_id", "functional_lead_id", "tech_lead_id", "team_member_ids", "client_contact_ids", "validator_ids", "escalation_path"]},
            {"title": "Siguiente acción (obligatoria)", "fields": ["next_action", "next_action_owner_id", "next_action_date", "next_decision"]},
            {"title": "Salud", "fields": ["health_scope", "health_time", "health_capacity", "health_quality", "health_client", "health", "health_reason", "risk_level", "client_dependent"]},
            {"title": "Fechas · plan original vs vigente", "fields": ["date_start", "date_end_baseline", "date_end_current", "date_end_probable", "baseline_set_date"]},
            {"title": "Horas (sin tarifas)", "fields": ["hours_authorized", "hours_estimated", "hours_consumed", "hours_approved", "hours_remaining", "hours_pct", "wip_limit"]},
            {"title": "Pronósticos", "fields": ["burn_rate_week", "hours_depletion_forecast", "velocity_week", "forecast_end_by_velocity"]},
            {"title": "Señales de Administración", "fields": ["contract_state", "commercial_restriction"]},
        ],
        "tabs": [{"field": "milestone_ids", "resource": "milestones", "parent_field": "project_id", "label": "Hitos"}, {"field": "item_ids", "resource": "items", "parent_field": "project_id", "label": "Backlog"},
                 {"field": "request_ids", "resource": "requests", "parent_field": "project_id", "label": "Solicitudes"}, {"field": "change_ids", "resource": "changes", "parent_field": "project_id", "label": "Cambios"},
                 {"field": "meeting_ids", "resource": "meetings", "parent_field": "project_id", "label": "Reuniones"}, {"field": "decision_ids", "resource": "decisions", "parent_field": "project_id", "label": "Decisiones"},
                 {"field": "raid_ids", "resource": "raid", "parent_field": "project_id", "label": "RAID"}, {"field": "incident_ids", "resource": "incidents", "parent_field": "project_id", "label": "Incidentes"},
                 {"field": "release_ids", "resource": "releases", "parent_field": "project_id", "label": "Liberaciones"}, {"field": "environment_ids", "resource": "environments", "parent_field": "project_id", "label": "Ambientes"},
                 {"field": "sprint_ids", "resource": "sprints", "parent_field": "project_id", "label": "Sprints"}, {"field": "document_ids", "resource": "documents", "parent_field": "project_id", "label": "Documentación"},
                 {"field": "link_ids", "resource": "links", "parent_field": "project_id", "label": "Accesos directos"}, {"field": "report_ids", "resource": "status_reports", "parent_field": "project_id", "label": "Reportes de estado"}],
        "actions": [{"name": "action_start", "label": "Inicio formal del proyecto", "roles": LEADS}, {"name": "action_set_baseline", "label": "Fijar línea base", "roles": LEADS},
                    {"name": "action_generate_status_report", "label": "Generar reporte semanal", "roles": INTERNAL}, {"name": "action_ready_to_close", "label": "Listo para cierre", "roles": LEADS},
                    {"name": "action_export_sheet", "label": "Exportar portafolio a Google Sheets", "roles": LEADS},
                    {"name": "action_assign_missing_folios", "label": "Asignar folios faltantes a sus sesiones", "roles": LEADS}],
        "client_hidden": CLIENT_HIDDEN_COMMON + ["team_member_ids", "health_capacity", "wip_limit", "burn_rate_week", "hours_depletion_forecast", "velocity_week", "forecast_end_by_velocity", "hours_estimated", "hours_consumed", "hours_approved", "hours_remaining", "hours_pct", "hours_authorized", "risk_level", "admin_project_ref", "admin_project_id", "template_id"],
        "roles": {"read": EVERYONE, "write": LEADS, "create": FULL + ["pm"], "delete": FULL},
    },
    "milestones": {"model": "aq.ops.milestone", "label": "Hitos", "singular": "Hito", "section": "trabajo", "order": 15, "scope": "project_id", "chatter": True,
                   "list": ["project_id", "name", "date_baseline", "date_current", "date_actual", "deviation_days", "state", "owner_id", "enables_billing"],
                   "filters": ["state", "project_id", "enables_billing"],
                   "groups": [{"title": "Hito", "fields": ["name", "project_id", "sequence", "description", "state", "owner_id", "validator_id", "enables_billing", "client_visible"]},
                              {"title": "Fechas", "fields": ["date_baseline", "date_current", "date_actual", "deviation_days", "validated_date"]},
                              {"title": "Siguiente acción", "fields": ["next_action", "next_action_date"]}],
                   "actions": [{"name": "action_validated", "label": "Registrar validación del cliente", "roles": LEADS}],
                   "client_hidden": CLIENT_HIDDEN_COMMON, "roles": {"read": EVERYONE, "write": INTERNAL, "create": LEADS, "delete": FULL}},
    "requests": {
        "model": "aq.ops.request", "label": "Solicitudes", "singular": "Solicitud", "section": "trabajo", "order": 20, "attachments": True, "chatter": True, "scope": "project_id", "org_field": "partner_id",
        "essential": ["name", "description", "partner_id", "project_id", "source", "urgency", "request_type", "scope_decision", "state", "ai_suggestion"],
        "list": ["name", "partner_id", "project_id", "source", "request_type", "urgency", "scope_decision", "state", "assignee_id", "create_date"],
        "filters": ["state", "request_type", "scope_decision", "urgency", "source", "project_id", "partner_id", "assignee_id"],
        "groups": [{"title": "Solicitud", "fields": ["name", "description", "source", "partner_id", "project_id", "requester_partner_id", "requester_department", "urgency", "client_visible"]},
                   {"title": "Clasificación y determinación", "fields": ["request_type", "scope_decision", "impact", "missing_info", "duplicate_of_id", "potential_duplicate_ids", "assignee_id", "state"]},
                   {"title": "Respuesta", "fields": ["response", "response_date", "first_response_hours", "item_id", "change_id", "incident_id"]}],
        "tabs": [{"field": "comment_ids", "resource": "comments", "parent_field": "request_id", "label": "Conversación"}],
        "actions": [{"name": "action_classify", "label": "Clasificar y determinar", "roles": INTERNAL}, {"name": "action_convert_item", "label": "Convertir en elemento de trabajo", "roles": INTERNAL},
                    {"name": "action_convert_change", "label": "Convertir en cambio de alcance", "roles": INTERNAL}, {"name": "action_convert_incident", "label": "Convertir en incidente", "roles": INTERNAL},
                    {"name": "action_respond", "label": "Responder al solicitante", "roles": INTERNAL}, {"name": "action_reject", "label": "Rechazar", "roles": LEADS}],
        "client_hidden": CLIENT_HIDDEN_COMMON + ["impact", "assignee_id", "potential_duplicate_ids", "duplicate_of_id", "scope_decision", "first_response_hours", "ai_suggestion"],
        "client_editable": ["name", "description", "urgency", "requester_department"],
        "roles": {"read": EVERYONE, "write": INTERNAL, "create": TEAM + CLIENT, "delete": FULL},
    },
    "items": {
        "model": "aq.ops.item", "label": "Backlog y trabajo", "singular": "Elemento", "section": "trabajo", "order": 30, "attachments": True, "chatter": True, "scope": "project_id",
        "essential": ["name", "project_id", "item_type", "state", "assignee_id", "date_due", "estimate_hours", "acceptance_criteria", "description"],
        "list": ["name", "item_type", "project_id", "state", "assignee_id", "priority", "date_due", "estimate_hours", "remaining_hours", "spent_hours", "sprint_id", "milestone_id", "waiting_client"],
        "filters": ["item_type", "state", "project_id", "assignee_id", "priority", "sprint_id", "milestone_id", "waiting_client", "client_visible", "unplanned", "is_rework"],
        "groups": [{"title": "Elemento", "fields": ["name", "item_type", "project_id", "parent_id", "deliverable_id", "milestone_id", "sprint_id", "description", "acceptance_criteria", "tags", "client_visible"]},
                   {"title": "Ejecución", "fields": ["state", "assignee_id", "reviewer_id", "priority", "rank", "blocked_reason", "waiting_client", "unplanned", "is_recurring", "recurrence_days", "is_rework", "found_in"]},
                   {"title": "Planeación (plan original vs vigente)", "fields": ["date_start", "date_due", "date_baseline", "reschedule_count", "reschedule_reason", "estimate_hours", "remaining_hours", "spent_hours", "depends_on_ids", "dependent_ids"]},
                   {"title": "Validación", "fields": ["validator_partner_id", "validator_department", "evidence", "accepted", "accepted_date", "request_id", "change_id", "meeting_id", "decision_id", "release_id", "incident_id"]},
                   {"title": "Flujo", "fields": ["days_in_state", "age_days", "blocked_hours", "cycle_days", "lead_days", "internal_notes"]}],
        "tabs": [{"field": "child_ids", "resource": "items", "parent_field": "parent_id", "label": "Hijos"}, {"field": "test_case_ids", "resource": "test_cases", "parent_field": "item_id", "label": "Casos de prueba"},
                 {"field": "acceptance_ids", "resource": "acceptances", "parent_field": "item_id", "label": "Validaciones"}, {"field": "timesheet_ids", "resource": "timesheets", "parent_field": "item_id", "label": "Tiempo"},
                 {"field": "comment_ids", "resource": "comments", "parent_field": "item_id", "label": "Comunicación"}],
        "actions": [{"name": "action_block", "label": "Bloquear", "roles": TEAM}, {"name": "action_unblock", "label": "Desbloquear", "roles": TEAM}, {"name": "action_ready_for_validation", "label": "Listo para validación", "roles": INTERNAL}],
        "client_hidden": CLIENT_HIDDEN_COMMON + ["assignee_id", "reviewer_id", "rank", "depends_on_ids", "dependent_ids", "cycle_days", "lead_days", "age_days", "days_in_state", "blocked_hours", "is_recurring", "recurrence_days"],
        "roles": {"read": EVERYONE, "write": TEAM, "create": INTERNAL, "delete": LEADS},
    },
    "changes": {"model": "aq.ops.change", "label": "Cambios de alcance", "singular": "Cambio", "section": "gobierno", "order": 10, "chatter": True, "attachments": True, "scope": "project_id",
                "list": ["name", "project_id", "requested_by", "estimate_hours", "estimate_approved", "state", "commercial_ref", "authorized_hours"],
                "filters": ["state", "project_id", "estimate_approved"],
                "groups": [{"title": "Cambio", "fields": ["name", "project_id", "request_id", "meeting_id", "requested_by", "description", "client_visible"]},
                           {"title": "Análisis, impacto y estimación", "fields": ["scope_analysis", "impact", "estimate_hours", "estimated_by_id", "estimate_approved"]},
                           {"title": "Autorización comercial (Administración)", "fields": ["state", "commercial_ref", "authorized_hours"]}],
                "tabs": [{"field": "item_ids", "resource": "items", "parent_field": "change_id", "label": "Elementos"}],
                "actions": [{"name": "action_send_commercial", "label": "Enviar a autorización comercial", "roles": LEADS}, {"name": "action_incorporate", "label": "Incorporar al backlog", "roles": LEADS},
                            {"name": "action_accepted", "label": "Aceptado → evento facturable", "roles": LEADS}],
                "client_hidden": CLIENT_HIDDEN_COMMON + ["scope_analysis", "estimated_by_id", "estimate_approved", "authorized_hours"],
                "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": FULL}},
    "meetings": {"model": "aq.ops.meeting", "label": "Reuniones y minutas", "singular": "Reunión", "section": "gobierno", "order": 20, "attachments": True, "chatter": True, "scope": "project_id",
                 "list": ["date", "folio", "name", "project_id", "session_type_id", "state", "processed", "followups_count", "summary_doc_url"],
                 "filters": ["meeting_type", "session_type_id", "state", "project_id", "processed", "imported"],
                 "essential": ["name", "project_id", "date", "session_type_id", "meeting_type", "location", "agenda", "state"],
                 "groups": [{"title": "Reunión", "fields": ["name", "project_id", "date", "meeting_type", "member_ids", "client_partner_ids", "next_meeting_date", "state", "client_visible", "location", "google_event_id", "meet_code", "google_doc_url"]},
                            {"title": "Seguimiento generado", "fields": ["processed", "followups_count", "followups_log", "summary_doc_url", "summary_sent", "exec_summary"]},
                            {"title": "Agenda y minuta", "fields": ["agenda", "minutes"]}, {"title": "Transcripción (evidencia histórica)", "fields": ["transcript", "ai_summary"]}],
                 "tabs": [{"field": "agreement_ids", "resource": "agreements", "parent_field": "meeting_id", "label": "Acuerdos y compromisos"}, {"field": "decision_ids", "resource": "decisions", "parent_field": "meeting_id", "label": "Decisiones"},
                          {"field": "question_ids", "resource": "questions", "parent_field": "meeting_id", "label": "Preguntas abiertas"}, {"field": "raid_ids", "resource": "raid", "parent_field": "meeting_id", "label": "Riesgos"},
                          {"field": "item_ids", "resource": "items", "parent_field": "meeting_id", "label": "Tareas"}, {"field": "change_ids", "resource": "changes", "parent_field": "meeting_id", "label": "Cambios"}],
                 "actions": [{"name": "action_mark_done", "label": "Marcar realizada", "roles": TEAM}, {"name": "action_send_minutes", "label": "Enviar minuta", "roles": INTERNAL}, {"name": "action_create_google_doc", "label": "Crear minuta en Google Docs", "roles": INTERNAL}, {"name": "action_process_ai", "label": "Procesar con IA (resumen ejecutivo + Doc + correo + actividades)", "roles": INTERNAL},
                             {"name": "action_assign_folio", "label": "Asignar folio del consecutivo", "roles": INTERNAL}],
                 "client_hidden": CLIENT_HIDDEN_COMMON, "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "agreements": {"model": "aq.ops.meeting.agreement", "label": "Acuerdos", "singular": "Acuerdo", "section": None, "scope": "meeting_id.project_id",
                   "list": ["name", "kind", "owner_id", "owner_partner_id", "due_date", "proposed_by_ai", "confirmed", "item_id", "is_contractual"],
                   "groups": [{"title": "Acuerdo", "fields": ["name", "kind", "owner_id", "owner_partner_id", "due_date", "proposed_by_ai", "confirmed", "is_contractual", "item_id", "change_id"]}],
                   "actions": [{"name": "action_confirm", "label": "Confirmar (crea tarea/cambio)", "roles": INTERNAL}],
                   "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": INTERNAL}},
    "questions": {"model": "aq.ops.meeting.question", "label": "Preguntas abiertas", "singular": "Pregunta", "section": None, "scope": "meeting_id.project_id",
                  "list": ["name", "owner_partner_id", "owner_id", "answered", "answer"],
                  "groups": [{"title": "Pregunta", "fields": ["name", "owner_partner_id", "owner_id", "answer", "answered", "client_visible"]}],
                  "client_editable": ["answer", "answered"], "roles": {"read": EVERYONE, "write": TEAM + CLIENT, "create": INTERNAL, "delete": INTERNAL}},
    "decisions": {"model": "aq.ops.decision", "label": "Decisiones", "singular": "Decisión", "section": "gobierno", "order": 30, "chatter": True, "scope": "project_id",
                  "list": ["date", "name", "project_id", "decided_by_id", "decided_by_partner_id", "version", "state", "replaces_id"],
                  "filters": ["state", "project_id"],
                  "groups": [{"title": "Decisión", "fields": ["name", "project_id", "meeting_id", "date", "context_text", "decision_text", "decided_by_id", "decided_by_partner_id", "affected_item_ids", "client_visible"]},
                             {"title": "Versionado", "fields": ["version", "replaces_id", "superseded_by_id", "state", "approved_date", "approver_user_id"]}],
                  "actions": [{"name": "action_approve", "label": "Aprobar (queda inmutable)", "roles": LEADS + CLIENT_APPROVERS}, {"name": "action_new_version", "label": "Nueva versión", "roles": LEADS}],
                  "client_hidden": CLIENT_HIDDEN_COMMON, "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": FULL}},
    "raid": {"model": "aq.ops.raid", "label": "RAID · riesgos, supuestos, problemas, dependencias", "singular": "Registro RAID", "section": "gobierno", "order": 40, "chatter": True, "scope": "project_id",
             "essential": ["name", "raid_type", "project_id", "probability", "impact", "owner_id", "next_action", "next_action_date", "state"],
             "list": ["raid_type", "name", "project_id", "probability", "impact", "severity", "owner_id", "requires_client", "next_action_date", "state", "endangers_date"],
             "filters": ["raid_type", "state", "project_id", "owner_id", "requires_client", "endangers_date"],
             "groups": [{"title": "Registro", "fields": ["name", "raid_type", "project_id", "meeting_id", "description", "probability", "impact", "severity", "state", "client_visible"]},
                        {"title": "Responsables y plan", "fields": ["owner_id", "requires_client", "client_owner_id", "mitigation", "next_action", "next_action_date", "due_date"]},
                        {"title": "Dependencias", "fields": ["depends_on_project_id", "depends_on_item_id", "affects_item_ids", "endangers_date"]}],
             "client_hidden": CLIENT_HIDDEN_COMMON + ["owner_id", "probability"], "roles": {"read": EVERYONE, "write": TEAM, "create": TEAM, "delete": LEADS}},
    "incidents": {"model": "aq.ops.incident", "label": "Incidentes productivos", "singular": "Incidente", "section": "gobierno", "order": 50, "attachments": True, "chatter": True, "scope": "project_id", "org_field": "partner_id",
                  "essential": ["name", "project_id", "partner_id", "severity", "step", "owner_id", "description"],
                  "list": ["name", "partner_id", "project_id", "severity", "step", "owner_id", "reported_at", "sla_breached", "affects_other_clients"],
                  "filters": ["severity", "step", "project_id", "partner_id", "owner_id", "sla_breached", "affects_other_clients"],
                  "groups": [{"title": "Incidente", "fields": ["name", "project_id", "partner_id", "request_id", "description", "severity", "step", "owner_id", "reported_at", "affects_other_clients", "client_visible"]},
                             {"title": "SLA", "fields": ["sla_response_hours", "sla_resolution_hours", "responded_at", "contained_at", "resolved_at", "closed_at", "sla_response_met", "sla_resolution_met", "sla_breached"]},
                             {"title": "Flujo (11 pasos)", "fields": ["containment", "diagnosis", "correction", "test_evidence", "release_id", "verification", "communication", "rca", "preventive_action", "preventive_item_id"]},
                             {"title": "Interno", "fields": ["internal_notes"]}],
                  "tabs": [{"field": "comment_ids", "resource": "comments", "parent_field": "incident_id", "label": "Bitácora"}, {"field": "item_ids", "resource": "items", "parent_field": "incident_id", "label": "Elementos"}],
                  "actions": [{"name": "action_advance", "label": "Avanzar al siguiente paso", "roles": INTERNAL}],
                  "client_hidden": CLIENT_HIDDEN_COMMON + ["owner_id", "diagnosis", "rca", "affects_other_clients"], "roles": {"read": EVERYONE, "write": INTERNAL, "create": TEAM + CLIENT, "delete": FULL}},
    "test_plans": {"model": "aq.ops.test.plan", "label": "Planes de prueba", "singular": "Plan", "section": "calidad", "order": 10, "scope": "project_id",
                   "list": ["name", "project_id", "plan_type", "environment_id", "state", "pass_pct"], "filters": ["plan_type", "state", "project_id"],
                   "groups": [{"title": "Plan", "fields": ["name", "project_id", "plan_type", "environment_id", "state", "pass_pct"]}],
                   "tabs": [{"field": "case_ids", "resource": "test_cases", "parent_field": "plan_id", "label": "Casos"}],
                   "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "test_cases": {"model": "aq.ops.test.case", "label": "Casos de prueba", "singular": "Caso", "section": "calidad", "order": 20, "scope": "project_id",
                   "list": ["name", "project_id", "item_id", "plan_id", "department", "last_result", "generated_by_ai"], "filters": ["last_result", "project_id", "plan_id", "department"],
                   "groups": [{"title": "Caso", "fields": ["name", "project_id", "plan_id", "item_id", "department", "steps", "expected", "last_result", "generated_by_ai", "client_visible"]}],
                   "tabs": [{"field": "run_ids", "resource": "test_runs", "parent_field": "case_id", "label": "Ejecuciones"}],
                   "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "test_runs": {"model": "aq.ops.test.run", "label": "Ejecuciones", "singular": "Ejecución", "section": None, "scope": "case_id.project_id",
                  "list": ["create_date", "result", "environment_id", "executed_by_id", "executed_by_partner_id", "is_retest", "defect_item_id"],
                  "groups": [{"title": "Ejecución", "fields": ["result", "environment_id", "evidence", "executed_by_id", "executed_by_partner_id", "is_retest", "defect_item_id"]}],
                  "roles": {"read": EVERYONE, "write": INTERNAL, "create": TEAM + CLIENT_APPROVERS, "delete": LEADS}},
    "acceptances": {"model": "aq.ops.acceptance", "label": "Validaciones y aceptación", "singular": "Validación", "section": "calidad", "order": 30, "attachments": True, "scope": "project_id",
                    "list": ["project_id", "item_id", "milestone_id", "validator_partner_id", "department", "requested_at", "due_date", "decision", "decided_at", "signature_hash"],
                    "filters": ["decision", "project_id", "department"],
                    "groups": [{"title": "Qué se valida", "fields": ["project_id", "item_id", "milestone_id", "release_id", "validator_partner_id", "department", "due_date", "requested_at"]},
                               {"title": "Criterios y evidencia", "fields": ["criteria", "evidence"]},
                               {"title": "Decisión (inmutable)", "fields": ["decision", "reason", "decided_at", "validator_user_id", "signature_hash", "reassigned_count"]}],
                    "client_hidden": ["reassigned_count"], "roles": {"read": EVERYONE, "write": LEADS, "create": INTERNAL, "delete": []}},
    "releases": {"model": "aq.ops.release", "label": "Liberaciones", "singular": "Liberación", "section": "calidad", "order": 40, "attachments": True, "chatter": True, "scope": "project_id",
                 "list": ["name", "project_id", "environment_id", "env_type", "planned_at", "owner_id", "backup_verified", "approved_by_id", "state", "success"],
                 "filters": ["state", "env_type", "project_id", "owner_id"],
                 "groups": [{"title": "Paquete", "fields": ["name", "project_id", "environment_id", "env_type", "owner_id", "planned_at", "maintenance_window", "state", "client_visible"]},
                            {"title": "Compuerta de liberación", "fields": ["backup_verified", "backup_ref", "test_evidence", "approvals_required", "approved_by_id", "approved_at", "rollback_plan", "gate_missing"]},
                            {"title": "Ejecución", "fields": ["plan", "deploy_log", "deployed_at", "post_verification", "verified_at", "review_item_id", "success"]}],
                 "tabs": [{"field": "item_ids", "resource": "items", "parent_field": "release_id", "label": "Funcionalidades y correcciones"}, {"field": "incident_ids", "resource": "incidents", "parent_field": "release_id", "label": "Incidencias"}],
                 "actions": [{"name": "action_approve", "label": "Aprobar liberación", "roles": LEADS}, {"name": "action_deploy", "label": "Desplegar (valida compuerta)", "roles": INTERNAL},
                             {"name": "action_verify", "label": "Verificación posterior OK", "roles": INTERNAL}, {"name": "action_rollback", "label": "Revertir", "roles": INTERNAL}],
                 "client_hidden": CLIENT_HIDDEN_COMMON + ["deploy_log", "rollback_plan", "backup_ref"], "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": FULL}},
    "environments": {"model": "aq.ops.environment", "label": "Ambientes", "singular": "Ambiente", "section": None, "scope": "project_id",
                     "list": ["name", "env_type", "url", "version", "last_deploy"], "groups": [{"title": "Ambiente", "fields": ["name", "env_type", "url", "version", "last_deploy", "notes"]}],
                     "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "sprints": {"model": "aq.ops.sprint", "label": "Sprints", "singular": "Sprint", "section": "trabajo", "order": 40, "scope": "project_id",
                "list": ["name", "project_id", "date_start", "date_end", "state", "item_count", "done_count", "committed_hours", "capacity_hours"], "filters": ["state", "project_id"],
                "groups": [{"title": "Sprint", "fields": ["name", "project_id", "goal", "date_start", "date_end", "capacity_hours", "committed_hours", "item_count", "done_count", "state"]}],
                "tabs": [{"field": "item_ids", "resource": "items", "parent_field": "sprint_id", "label": "Elementos"}],
                "roles": {"read": TEAM, "write": INTERNAL, "create": LEADS, "delete": LEADS}},
    "timesheets": {"model": "aq.ops.timesheet", "label": "Registro de tiempo", "singular": "Registro", "section": "tiempo", "order": 10, "scope": "project_id",
                   "list": ["date", "member_id", "project_id", "item_id", "hours", "category", "billable", "state", "unjustified"], "filters": ["state", "member_id", "project_id", "category", "billable", "week", "unjustified"],
                   "groups": [{"title": "Registro", "fields": ["member_id", "project_id", "item_id", "date", "hours", "category", "billable", "description", "justification", "week"]},
                              {"title": "Aprobación", "fields": ["state", "approved_by_id", "approved_at", "reject_reason"]}],
                   "actions": [{"name": "action_submit", "label": "Enviar a aprobación", "roles": TEAM}, {"name": "action_approve", "label": "Aprobar", "roles": LEADS}, {"name": "action_reject", "label": "Rechazar", "roles": LEADS}],
                   "roles": {"read": TEAM, "write": TEAM, "create": TEAM, "delete": LEADS}},
    "capacity": {"model": "aq.ops.capacity", "label": "Capacidad y carga", "singular": "Capacidad", "section": "tiempo", "order": 20, "scope": None,
                 "list": ["week", "member_id", "specialty", "hours_available", "unavailable_hours", "planned_hours", "logged_hours", "load_pct", "overallocated"], "filters": ["week", "member_id", "specialty", "overallocated"],
                 "groups": [{"title": "Capacidad", "fields": ["member_id", "week", "specialty", "hours_available", "unavailable_hours", "unavailability_reason", "planned_hours", "logged_hours", "load_pct", "overallocated"]}],
                 "roles": {"read": INTERNAL, "write": LEADS, "create": LEADS, "delete": LEADS}},
    "documents": {"model": "aq.ops.document", "label": "Conocimiento y documentación", "singular": "Documento", "section": "conocimiento", "order": 10, "attachments": True, "chatter": True, "scope": "project_id",
                  "list": ["doc_type", "name", "project_id", "version", "is_current", "is_canonical", "owner_id", "client_visible"], "filters": ["doc_type", "project_id", "is_current", "is_canonical", "client_visible"],
                  "groups": [{"title": "Documento", "fields": ["name", "doc_type", "project_id", "drive_url", "drive_file_id", "owner_id", "summary", "client_visible"]},
                             {"title": "Versiones lógicas", "fields": ["version", "is_current", "is_canonical", "replaces_id", "superseded_by_id", "item_ids", "decision_id", "meeting_id"]}],
                  "actions": [{"name": "action_new_version", "label": "Nueva versión (reemplaza la vigente)", "roles": INTERNAL}],
                  "client_hidden": CLIENT_HIDDEN_COMMON + ["drive_file_id"], "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "comments": {"model": "aq.ops.comment", "label": "Comentarios", "singular": "Comentario", "section": None, "scope": None,
                 "list": ["create_date", "author_user_id", "internal", "body"], "groups": [{"title": "Comentario", "fields": ["body", "internal", "mention_ids"]}],
                 "client_hidden": ["mention_ids"], "client_editable": ["body"], "roles": {"read": EVERYONE, "write": [], "create": EVERYONE, "delete": LEADS}},
    "links": {"model": "aq.ops.link", "label": "Accesos directos", "singular": "Acceso", "section": None, "scope": "project_id",
              "list": ["name", "link_type", "url", "client_visible"], "groups": [{"title": "Acceso", "fields": ["name", "url", "link_type", "client_visible"]}],
              "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": INTERNAL}},
    "status_reports": {"model": "aq.ops.status.report", "label": "Reportes de estado", "singular": "Reporte", "section": "conocimiento", "order": 20, "scope": "project_id",
                       "list": ["date", "name", "project_id", "health", "generated_by_ai", "client_visible", "sent_date"], "filters": ["project_id", "health"],
                       "groups": [{"title": "Reporte", "fields": ["name", "project_id", "date", "health", "client_visible", "generated_by_ai", "sent_date"]}, {"title": "Contenido", "fields": ["summary"]}],
                       "roles": {"read": EVERYONE, "write": INTERNAL, "create": INTERNAL, "delete": LEADS}},
    "templates": {"model": "aq.ops.template", "label": "Plantillas de proyecto", "singular": "Plantilla", "section": "config", "order": 10, "scope": None,
                  "list": ["sequence", "name", "service_type", "methodology", "wip_limit"], "groups": [{"title": "Plantilla", "fields": ["name", "service_type", "methodology", "description", "wip_limit", "sequence"]}],
                  "tabs": [{"field": "phase_ids", "resource": "template_phases", "parent_field": "template_id", "label": "Fases / hitos"}, {"field": "item_ids", "resource": "template_items", "parent_field": "template_id", "label": "Elementos iniciales"}],
                  "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL}},
    "template_phases": {"model": "aq.ops.template.phase", "label": "Fases", "singular": "Fase", "section": None, "scope": None, "list": ["sequence", "name", "offset_days", "enables_billing"],
                        "groups": [{"title": "Fase", "fields": ["sequence", "name", "offset_days", "enables_billing"]}], "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL}},
    "template_items": {"model": "aq.ops.template.item", "label": "Elementos", "singular": "Elemento", "section": None, "scope": None, "list": ["sequence", "name", "item_type", "estimate_hours"],
                       "groups": [{"title": "Elemento", "fields": ["sequence", "name", "item_type", "acceptance_criteria", "estimate_hours"]}], "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL}},
    "automations": {"model": "aq.ops.automation", "label": "Automatizaciones", "singular": "Automatización", "section": "config", "order": 20, "scope": None,
                    "list": ["sequence", "name", "trigger", "action_type", "owner_id", "critical", "active", "last_run", "run_count"], "filters": ["trigger", "action_type", "active", "critical"],
                    "groups": [{"title": "Regla", "fields": ["name", "description", "trigger", "model_name", "condition_domain", "action_type", "action_params", "code"]},
                               {"title": "Gobierno", "fields": ["owner_id", "critical", "active", "sequence", "last_run", "run_count"]}],
                    "tabs": [{"field": "log_ids", "resource": "automation_logs", "parent_field": "automation_id", "label": "Historial de ejecución"}],
                    "actions": [{"name": "run", "label": "Ejecutar ahora", "roles": FULL}], "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL}},
    "automation_logs": {"model": "aq.ops.automation.log", "label": "Ejecuciones", "singular": "Ejecución", "section": None, "scope": None, "list": ["create_date", "result", "affected", "detail"],
                        "groups": [{"title": "Ejecución", "fields": ["result", "affected", "detail"]}], "roles": {"read": INTERNAL, "write": [], "create": [], "delete": []}},
    "events": {"model": "aq.ops.event", "label": "Eventos Administración ⇄ Operaciones", "singular": "Evento", "section": "config", "order": 30, "scope": "ops_project_id",
               "list": ["create_date", "direction", "event_type", "summary", "state", "processed_at"], "filters": ["direction", "event_type", "state"],
               "groups": [{"title": "Evento", "fields": ["direction", "event_type", "ops_project_id", "admin_project_id", "payload", "state", "processed_at", "error"]}],
               "actions": [{"name": "process", "label": "Reprocesar", "roles": FULL}], "roles": {"read": LEADS + ["admin_liaison"], "write": [], "create": FULL, "delete": []}},
    "integrations": {"model": "aq.ops.integration", "label": "Integraciones autorizadas", "singular": "Integración", "section": "config", "order": 40, "scope": None,
                     "list": ["name", "kind", "enabled", "model", "owner_id", "last_used"], "groups": [{"title": "Integración", "fields": ["name", "kind", "enabled", "base_url", "api_key", "model", "webhook_url", "owner_id", "notes", "last_used"]}],
                     "roles": {"read": ["platform_owner"], "write": ["platform_owner"], "create": ["platform_owner"], "delete": ["platform_owner"]}},
    "breakglass": {"model": "aq.ops.breakglass", "label": "Acceso extraordinario (break glass)", "singular": "Solicitud", "section": "config", "order": 50, "scope": None,
                   "list": ["create_date", "user_id", "granted_role", "project_id", "start", "end", "state", "approved_by_id"], "filters": ["state"],
                   "groups": [{"title": "Solicitud", "fields": ["user_id", "justification", "granted_role", "project_id", "start", "end", "state", "approved_by_id", "actions_log"]}],
                   "actions": [{"name": "action_approve", "label": "Aprobar", "roles": ["platform_owner"]}, {"name": "action_revoke", "label": "Revocar", "roles": ["platform_owner"]}],
                   "roles": {"read": ["platform_owner", "ops_director"], "write": ["platform_owner"], "create": INTERNAL, "delete": []}},
    "google_inbox": {
        "model": "aq.google.message", "label": "Bandeja de reuniones y correo (Google)", "singular": "Mensaje", "section": "conocimiento", "order": 5, "scope": None,
        "domain": [("app", "=", "ops")],
        "list": ["date", "source", "subject", "category", "project_id", "state", "summary_doc_url", "res_label"],
        "filters": ["state", "category", "source", "routed_by", "project_id"],
        "essential": ["subject", "project_id", "date", "source", "state", "summary_doc_url", "source_doc_url", "exec_summary"],
        "groups": [{"title": "Mensaje", "fields": ["subject", "sender", "recipients", "date", "source", "link", "attachment_names"]},
                   {"title": "Enrutamiento", "fields": ["app", "category", "routed_by", "rule_id", "partner_id", "project_id", "ai_summary", "ai_action", "state", "res_label"]},
                   {"title": "Resumen ejecutivo", "fields": ["exec_summary", "summary_doc_url", "source_doc_url"]},
                   {"title": "Transcripción", "fields": ["transcript"]},
                   {"title": "Correo original", "fields": ["body"]}],
        "actions": [{"name": "action_process_notes", "label": "Procesar transcripción (resumen + mi documento)", "roles": INTERNAL},
                    {"name": "action_assign_and_link", "label": "Vincular al proyecto asignado (reunión + actividades)", "roles": INTERNAL},
                    {"name": "action_to_ops_meeting", "label": "→ Reunión (notas/transcripción)", "roles": INTERNAL}, {"name": "action_to_ops_request", "label": "→ Solicitud", "roles": INTERNAL},
                    {"name": "action_to_ops_incident", "label": "→ Incidente", "roles": INTERNAL}, {"name": "action_to_ops_comment", "label": "→ Comunicación del proyecto", "roles": INTERNAL},
                    {"name": "action_ignore", "label": "Ignorar", "roles": INTERNAL}],
        "roles": {"read": INTERNAL, "write": INTERNAL, "create": [], "delete": FULL},
    },
    "ai_prompts": {
        "model": "aq.ai.prompt", "label": "Biblioteca de prompts (IA)", "singular": "Prompt", "section": "config", "order": 12, "scope": None, "chatter": True,
        "list": ["category", "sequence", "code", "name", "tier", "json_mode", "version", "use_count", "last_used", "active"],
        "filters": ["category", "tier", "active", "json_mode"],
        "essential": ["name", "code", "category", "tier", "purpose", "system_prompt", "user_template"],
        "groups": [{"title": "Identidad", "fields": ["name", "code", "category", "sequence", "tier", "active", "version", "variables_hint", "use_count", "last_used"]},
                   {"title": "Instrucciones", "fields": ["purpose", "system_prompt", "user_template"]},
                   {"title": "Salida", "fields": ["json_mode", "json_schema_hint", "max_tokens", "temperature", "include_brand_voice"]},
                   {"title": "Prueba", "fields": ["last_output"]}],
        "actions": [{"name": "action_test", "label": "Probar con datos de ejemplo", "roles": FULL}, {"name": "action_duplicate_version", "label": "Duplicar como nueva versión", "roles": FULL}],
        "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL},
    },
    "session_types": {
        "model": "aq.ops.session.type", "label": "Tipos de sesión", "singular": "Tipo", "section": "config", "order": 15, "scope": None,
        "list": ["sequence", "name", "code", "duration_minutes", "meeting_type", "invite_team", "invite_client", "auto_process", "client_visible"],
        "groups": [{"title": "Tipo de sesión", "fields": ["name", "code", "sequence", "duration_minutes", "meeting_type", "invite_team", "invite_client", "client_visible", "auto_process", "agenda_template"]}],
        "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL},
    },
    "google_rules": {
        "model": "aq.google.rule", "label": "Reglas de enrutamiento de correo", "singular": "Regla", "section": "config", "order": 45, "scope": None,
        "list": ["sequence", "name", "match_from", "match_subject", "match_keywords", "target_app", "target_type", "auto_convert", "active"],
        "filters": ["target_app", "target_type", "active"],
        "groups": [{"title": "Regla", "fields": ["name", "sequence", "active", "notes"]}, {"title": "Coincidencia", "fields": ["match_from", "match_to", "match_subject", "match_keywords", "match_label"]},
                   {"title": "Destino", "fields": ["target_app", "target_type", "auto_convert", "project_id", "partner_id"]}],
        "roles": {"read": INTERNAL, "write": FULL, "create": FULL, "delete": FULL},
    },
    "saved_views": {"model": "aq.ops.saved.view", "label": "Vistas guardadas", "singular": "Vista", "section": None, "scope": None, "list": ["name", "resource", "view_mode", "shared"],
                    "groups": [{"title": "Vista", "fields": ["name", "resource", "view_mode", "filters_json", "shared"]}], "roles": {"read": EVERYONE, "write": EVERYONE, "create": EVERYONE, "delete": EVERYONE}},
}

OPS_NAME_SEARCH_MODELS = {r["model"] for r in OPS_RESOURCES.values()} | {"res.partner", "aq.portal.member"}


def ops_resource_for_model(model):
    for k, r in OPS_RESOURCES.items():
        if r["model"] == model and r.get("section"):
            return k
    for k, r in OPS_RESOURCES.items():
        if r["model"] == model:
            return k
    return None
